performance:
  name: kurrentdb-local-write
  mode: write
  local: true
  warmup_seconds: 0
  duration_seconds: 5
  samples_per_second: 10
  concurrency:
    writers: [1, 2, 4, 8, 16, 32]
  operations:
    read:
      limit: 10
    write:
      event_size_bytes: 256
  setup:
    prepopulate_events: 500
    prepopulate_streams: 50
  stores:
    - kurrentdb
---
performance:
  name: kurrentdb-local-read
  mode: read
  local: true
  warmup_seconds: 0
  duration_seconds: 10
  samples_per_second: 10
  concurrency:
      readers: [1, 2, 4, 8, 16, 32]
  operations:
    read:
      limit: 10
    write:
      event_size_bytes: 256
  setup:
    prepopulate_events: 500
    prepopulate_streams: 50
  stores:
    - kurrentdb
