performance:
  name: writer-scaling-in-docker
  mode: write
  use_docker: true
  warmup_seconds: 0
  duration_seconds: 60
  samples_per_second: 5
  concurrency:
    readers: 0
    writers: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
  operations:
    write:
      event_size_bytes: 256
  stores:
    - umadb
    - kurrentdb
    - axonserver
    - eventsourcingdb
    - fact
#    - dummy
---
performance:
  name: reader-scaling-in-docker
  mode: read
  use_docker: true
  warmup_seconds: 0
  duration_seconds: 60
  samples_per_second: 5
  concurrency:
    readers: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
    writers: 0
  operations:
    write:
      event_size_bytes: 256
    read:
      limit: 10
  setup:
    prepopulate_events: 5000
    prepopulate_streams: 500
  stores:
    - umadb
    - kurrentdb
    - axonserver
    - eventsourcingdb
    - fact
#    - dummy
