performance:
  name: write-one-tag-one-type
  mode: write
  use_docker: false
  warmup_seconds: 1
  duration_seconds: 60
  samples_per_second: 2
  concurrency:
    readers: 0
    writers: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
#    writers: [1, 2, 4]
  operations:
    write:
      event_size_bytes: 256
      concurrency_control: true
      append_condition: one_tag_one_type

  stores:
    - umadb
    - axonserver
