name: "smoke-test"
workload_type: "performance"

mode: "write"

duration_seconds: 5

concurrency:
#  writers: [1, 4, 16]
  writers: [1, 16]

operations:
  write:
    event_size_bytes: 256

streams:
  distribution: "uniform"
  count: 100

stores: [umadb, dummy]
#stores: [umadb, kurrentdb, axonserver, eventsourcingdb, dummy]
