performance:
  name: smoke-test-performance-write
  mode: write
#  local: true
  warmup_seconds: 1
  duration_seconds: 3
  samples_per_second: 10
  concurrency:
    writers: [1, 4]
  operations:
    read:
      limit: 10
    write:
      event_size_bytes: 256
  setup:
    prepopulate_events: 500
    prepopulate_streams: 50
  stores:
    - umadb
    - kurrentdb
    - axonserver
    - eventsourcingdb
    - dummy
---
performance:
  name: smoke-test-performance-read
  mode: read
#  local: true
  warmup_seconds: 1
  duration_seconds: 3
  samples_per_second: 10
  concurrency:
    readers: [1, 4]
  operations:
    read:
      limit: 10
    write:
      event_size_bytes: 256
  setup:
    prepopulate_events: 500
    prepopulate_streams: 50
  stores:
    - umadb
    - kurrentdb
    - axonserver
    - eventsourcingdb
    - dummy
