name: Benchmark Suite

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      session_id: ${{ steps.session.outputs.session_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generate Session ID
        id: session
        run: echo "session_id=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Build benchmark tool
        run: make build

      - name: Upload benchmark tool
        uses: actions/upload-artifact@v6
        with:
          name: es-bench
          path: target/release/es-bench
          retention-days: 1

      - name: Upload configs
        uses: actions/upload-artifact@v6
        with:
          name: configs
          path: configs/
          retention-days: 1

      - name: Upload Makefile
        uses: actions/upload-artifact@v6
        with:
          name: Makefile
          path: Makefile
          retention-days: 1

  run-smoke-test:
    needs: setup
    runs-on: ubuntu-latest
    env:
      ESB_SESSION_ID: ${{ needs.setup.outputs.session_id }}-SMK
    steps:
      - name: Download benchmark tool
        uses: actions/download-artifact@v8
        with:
          name: es-bench
          path: target/release/

      - name: Download configs
        uses: actions/download-artifact@v8
        with:
          name: configs
          path: configs/

      - name: Download Makefile
        uses: actions/download-artifact@v8
        with:
          name: Makefile
          path: .

      - name: Make benchmark tool executable
        run: chmod +x target/release/es-bench

      - name: Run smoke-test workload  # sudo otherwise Axon Server files can't be deleted
        run: |
          sudo -E make run-smoke-test
          sudo chown -R $(id -u):$(id -g) ./results

      - name: Upload smoke-test results
        uses: actions/upload-artifact@v6
        with:
          name: results-smoke-test
          path: results/raw/
          retention-days: 1

  run-umadb-local:
    needs: setup
    runs-on: ubuntu-latest
    env:
      ESB_SESSION_ID: ${{ needs.setup.outputs.session_id }}-UMA
    steps:
      - name: Download benchmark tool
        uses: actions/download-artifact@v8
        with:
          name: es-bench
          path: target/release/

      - name: Download configs
        uses: actions/download-artifact@v8
        with:
          name: configs
          path: configs/

      - name: Download Makefile
        uses: actions/download-artifact@v8
        with:
          name: Makefile
          path: .

      - name: Make benchmark tool executable
        run: chmod +x target/release/es-bench

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install umadb
        run: make install-umadb

      - name: Start umadb
        run: make start-umadb

      - name: Run umadb-local workload
        run: make run-umadb-local

      - name: Upload umadb-local results
        uses: actions/upload-artifact@v6
        with:
          name: results-umadb-local
          path: results/raw/
          retention-days: 1

  run-kurrentdb-local:
    needs: setup
    runs-on: ubuntu-latest
    env:
      ESB_SESSION_ID: ${{ needs.setup.outputs.session_id }}-KUR
    steps:
      - name: Download benchmark tool
        uses: actions/download-artifact@v8
        with:
          name: es-bench
          path: target/release/

      - name: Download configs
        uses: actions/download-artifact@v8
        with:
          name: configs
          path: configs/

      - name: Download Makefile
        uses: actions/download-artifact@v8
        with:
          name: Makefile
          path: .

      - name: Make benchmark tool executable
        run: chmod +x target/release/es-bench

      - name: Install kurrentdb
        run: |
          curl -1sLf 'https://packages.kurrent.io/public/kurrent-lts/setup.deb.sh' | sudo -E bash
          apt-get install kurrentdb=26.0.2
          cat /etc/kurrentdb/kurrentdb.conf

      - name: Start kurrentdb
        run: |
          systemctl start kurrentdb
          sleep 15

      - name: Run kurrentdb-local workload
        run: make run-kurrentdb-local

      - name: Upload kurrentdb-local results
        uses: actions/upload-artifact@v6
        with:
          name: results-kurrentdb-local
          path: results/raw/
          retention-days: 1

#  run-scaling:
#    needs: setup
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        store: [umadb, kurrentdb, axonserver, eventsourcingdb, dummy]
#    env:
#      ESB_SESSION_ID: ${{ needs.setup.outputs.session_id }}-SCL
#      ESB_WORKLOAD_STORES: ${{ matrix.store }}
#    steps:
#      - name: Download benchmark tool
#        uses: actions/download-artifact@v8
#        with:
#          name: es-bench
#          path: target/release/
#
#      - name: Download configs
#        uses: actions/download-artifact@v8
#        with:
#          name: configs
#          path: configs/
#
#      - name: Download Makefile
#        uses: actions/download-artifact@v8
#        with:
#          name: Makefile
#          path: .
#
#      - name: Make benchmark tool executable
#        run: chmod +x target/release/es-bench
#
#      - name: Run scaling workload  # sudo otherwise Axon Server files can't be deleted
#        run: |
#          sudo -E make run-scaling
#          sudo chown -R $(id -u):$(id -g) ./results
#
#      - name: Upload scaling results
#        uses: actions/upload-artifact@v6
#        with:
#          name: results-scaling-${{ matrix.store }}
#          path: results/raw/
#          retention-days: 1

  report:
#    needs: [run-smoke-test, run-scaling]
    needs: [run-smoke-test, run-umadb-local, run-kurrentdb-local]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'python/requirements.txt'

      - name: Create Python virtual environment for reporting
        run: make venv

      - name: Download results
        uses: actions/download-artifact@v8
        with:
          pattern: results-*
          path: results/raw/
          merge-multiple: true

      - name: Generate report
        run: make report

      - name: Upload report artifact
        uses: actions/upload-artifact@v6
        with:
          name: benchmark-report
          path: results/published
