name: Scaling Postgres

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      session_id: ${{ steps.session.outputs.session_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generate Session ID
        id: session
        run: echo "session_id=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Build benchmark tool
        run: make build

      - name: Upload benchmark tool
        uses: actions/upload-artifact@v6
        with:
          name: es-bench
          path: target/release/es-bench
          retention-days: 1

      - name: Upload configs
        uses: actions/upload-artifact@v6
        with:
          name: configs
          path: configs/
          retention-days: 1

      - name: Upload Makefile
        uses: actions/upload-artifact@v6
        with:
          name: Makefile
          path: Makefile
          retention-days: 1

  run-scaling-postgres:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        store: [marten, py-eventsourcing, umadb]
    env:
      ESB_SESSION_ID: ${{ needs.setup.outputs.session_id }}
      ESB_WORKLOAD_STORES: ${{ matrix.store }}
      ESB_GIT_VERSION: ${{ github.sha }}
    steps:
      - name: Setup database
        if: ${{ matrix.store == 'marten' || matrix.store == 'py-eventsourcing' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo systemctl status postgresql      
          
          sudo -u postgres psql -c 'CREATE DATABASE eventsourcing;'
          sudo -u postgres psql -c "CREATE USER eventsourcing WITH PASSWORD 'eventsourcing';"
          sudo -u postgres psql -c "ALTER DATABASE eventsourcing OWNER TO eventsourcing;"

      - name: Download benchmark tool
        uses: actions/download-artifact@v8
        with:
          name: es-bench
          path: target/release/

      - name: Download configs
        uses: actions/download-artifact@v8
        with:
          name: configs
          path: configs/

      - name: Make benchmark tool executable
        run: chmod +x target/release/es-bench

      - name: Download Makefile
        uses: actions/download-artifact@v8
        with:
          name: Makefile
          path: .

      - name: Create tables for Marten
        if: ${{ matrix.store == 'marten' }}
        run: ./target/release/es-bench create-marten-tables

      - name: Create tables for PyEventsourcing
        if: ${{ matrix.store == 'py-eventsourcing' }}
        run: ./target/release/es-bench create-py-eventsourcing-tables

      - name: Set up Rust
        if: ${{ matrix.store == 'umadb' }}
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install protobuf compiler
        if: ${{ matrix.store == 'umadb' }}
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install and start umadb
        if: ${{ matrix.store == 'umadb' }}
        run: |
          cargo install umadb@=0.5.3
          uUMADB_READ_METHOD=fileio UMADB_PAGE_CACHE_MAX_MB=3000 nohup madb &

      - name: Run scaling workload  # sudo otherwise Axon Server files can't be deleted
        run: |
          make run-scaling-postgres

      - name: Upload scaling results
        uses: actions/upload-artifact@v6
        with:
          name: results-scaling-${{ matrix.store }}
          path: results/raw/
          retention-days: 1

  report:
    needs: [setup, run-scaling-postgres]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'python/requirements.txt'

      - name: Create Python virtual environment for reporting
        run: make venv

      - name: Download results
        uses: actions/download-artifact@v8
        with:
          pattern: results-*
          path: results/raw/
          merge-multiple: true

      - name: Generate report
        run: make report

      - name: Upload report artifact
        uses: actions/upload-artifact@v6
        with:
          name: benchmark-report
          path: results/published
